### ISSUE TITLE
FR: change the wallpaper as well

### ISSUE THREAD

**Issue by Zahrun** [adrium/knightadjuster#6]
Would be great to be able to automatically change the wallpaper based on light/dark mode

**Comment by adrium** [comment]
Added support in 0f52794

Add the following lines to your knightadjusterrc:

    WALLPAPER_DARK=/full/path/to/image.jpg
    WALLPAPER_LIGHT=/full/path/to/image.jpg

**Comment by Zahrun** [comment]
Thank you!
