### ISSUE TITLE
License for knightadjuster?

### ISSUE THREAD

**Issue by sfalken** [adrium/knightadjuster#7]
I see you haven't declared which license you're releasing this under.   I have a couple projects that I'd like to use this in, but basically if no licensing is declared, I just assume that it's not redistributable, as do most projects.

**Comment by adrium** [comment]
Thanks for getting in touch about this. I am not a licensing expert that's why I have not set one. In what kind of projects would you like to use it? What license would you think is appropriate for this project?

**Comment by sfalken** [comment]
I personally want to package it for use in openSUSE, but this is a requirement for plenty of projects, to get software into their "official" respositories.

As far as licenses go, that sort of depends on your philosophy on FOSS.    If you want a "Hey, take this code, and use it, and don't worry about the details" Something like the [Apache-2.0](https://spdx.org/licenses/Apache-2.0.html), [MIT](https://spdx.org/licenses/MIT.html), or [BSD-3-Clause](https://spdx.org/licenses/BSD-3-Clause.html) licenses might fit.  

If you're wanting a more "copyleft" style license, where it theoretically assures that any derivative works are also licensed in a "Free" manner, you might look at [GPL-2.0-or-later](https://spdx.org/licenses/GPL-2.0-or-later.html) or [GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html).

Or you know, if you just don't want to worry about anything, there's always the [WTFPL](https://spdx.org/licenses/WTFPL.html), which in short boils down to "Go ahead, take this code, and do whatever you want with it, I don't care, and stop bothering me about it"

Any of the ones I listed are suitable for inclusion in the majority of FOSS projects, but if you want to have a look at the list of SPDX licenses, they can be found at https://spdx.org/licenses/

Github has [Choosealicense](https://choosealicense.com/) which walks you through a few questions to help you decide, if you're just not sure what you want to do.

**Comment by adrium** [comment]
Thanks a lot for the overview. I will add an MIT license file.

You can package it and it would be nice to reference it here.

**Comment by adrium** [comment]
Committed 02d8df2.
