### ISSUE TITLE
Plasma 6 compatibility

### ISSUE THREAD

**Issue by Zahrun** [adrium/knightadjuster#9]
```
qdbus org.kde.KWin /ColorCorrect org.kde.kwin.ColorCorrect.currentTemperature
Error: org.freedesktop.DBus.Error.UnknownObject
No such object path '/ColorCorrect'
```

**Comment by Zahrun** [comment]
```
qdbus org.kde.KWin /org/kde/KWin/NightLight org.kde.KWin.NightLight.currentTemperature 
6500
```

**Comment by adrium** [comment]
Thanks for your feedback and suggestion how to fix. What distro did you use to test it?

**Comment by Zahrun** [comment]
I’m using Tuxedo OS 2 with Plasma 5 and Garuda Linux (arch-based) with Plasma 6.
To keep the compatibility with both, I kept the test as 
```
if [ $(qdbus org.kde.KWin /org/kde/KWin/NightLight org.kde.KWin.NightLight.currentTemperature || qdbus org.kde.KWin /ColorCorrect org.kde.kwin.ColorCorrect.currentTemperature) -lt $THRESHOLD_DARK ]; then
```

**Comment by Alaric323** [comment]
I don't know if this is enough to solve Plasma 6.  qdbus is now qdbus6 for QT6 updates, so all references to qdbus have to be changed accordingly.  I made the changes (as well as Zahrun's above change but only for Plasma 6) to the below file.
[knightadjuster-qt6.txt](https://github.com/adrium/knightadjuster/files/15268646/knightadjuster-qt6.txt)

**Comment by adrium** [comment]
Thanks for your input.
I am a Kubuntu user and just installed 24.10 which uses Plasma 6.1, Qt 6.6, and Wayland. It works with keeping the qdbus command. Can you test the latest code?

**Comment by adrium** [comment]
Please reopen, if it is still incompatible
